## Numpy Basics

#### NumPy, short for Numerical Python

#### is one of the most important foundational packages for numerical computing in Python. 

#### Most computational packages providing scientific functionality use NumPy’s array objects

* ndarray, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.

* Mathematical functions for fast operations on entire arrays of data without having to write loops.

* Tools for reading/writing array data to disk and working with memory-mapped files.

* Linear algebra, random number generation, and Fourier transform capabilities.

* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

In [5]:
import numpy as np

#### Here's a comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [13]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

#arr1
#arr2

In [11]:
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

arr1_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [14]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 113 ms, sys: 0 ns, total: 113 ms
Wall time: 113 ms


833332333333500000

In [15]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 1.32 ms, sys: 610 µs, total: 1.93 ms
Wall time: 1.31 ms


833332333333500000

In [21]:
# Creating a numpy array

np_arr = np.array([1, 2, 3])

np_arr

array([1, 2, 3])

In [22]:
np_arr.dtype

dtype('int64')

In [26]:
# all elements of same type

np_arr = np.array(["hello", "world", 1, 2])

np_arr

array(['hello', 'world', '1', '2'], dtype='<U5')

In [27]:
# Can specify the dtype you want

np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [36]:
# Shape, Dimension and Size

np_arr = np.array([1, 2])

(np_arr.shape, np_arr.ndim, np_arr.size)

((2,), 1, 2)

In [34]:
np_arr = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

(np_arr.shape, np_arr.ndim, np_arr.size)

((3, 2), 2, 6)

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">

In [37]:
# Zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty((1, 3))

array([[0., 0., 0.]])

In [42]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Universal Functions

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. 

fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [43]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Unary ufuncs

In [44]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [45]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#### Binary ufuncs

In [49]:
a = np.array([1, 8, 3, 6])
b = np.array([5, 2, 7, 4])

In [47]:
np.maximum(a, b)

array([5, 6, 7, 8])

In [52]:
## Conditional Logic as Array Operations

a = np.array([1, 8, 3, 6])
b = np.array([5, 2, 7, 4])
c = np.array([False, True, False, True])

[(x if z else y) for x, y, z in zip(a, b, c)]

[5, 8, 7, 6]

In [53]:
np.where(c, a, b)

array([5, 8, 7, 6])

In [54]:
a > 3

array([False,  True, False,  True])

In [55]:
np.where(a > 3, 1, 0)

array([0, 1, 0, 1])

In [56]:
## Mathematical and Statistical Methods

In [59]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
arr / 2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [60]:
arr.mean()

4.5

In [62]:
arr.sum()

45

In [63]:
arr.sum(axis = 1)

array([10, 35])

In [64]:
arr.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [65]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [75]:
## Random numbers

In [73]:
np.random.seed(1234)

In [74]:
np.random.randn(5)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873])