In [1]:
import pandas as pd

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
titanic = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [3]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
titanic.tail()

PassengerId  Survived  Pclass                               Name     Sex  \
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
153          154         0       3    van Billiard, Mr. Austin Blyler    male   
154          155         0       3              Olsen, Mr. Ole Martin    male   
155          156         0       1        Williams, Mr. Charles Duane    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
151  22.0      1      0      113776  66.6000    C2        S  
152  55.5      0      0  A.5. 11206   8.0500   NaN        S  
153  40.5      0      2    A/5. 851  14.5000   NaN        S  
154   NaN      0      0   Fa 265302   7.3125   NaN        S  
155  51.0      0      1    PC 17597  61.3792   NaN        C

In [5]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [7]:
titanic.dtypes[titanic.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [8]:
titanic[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [9]:
sorted(titanic["Name"])

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond',
 'Beesley, Mr. Lawrence',
 'Bing, Mr. Lee',
 'Bonnell, Miss. Elizabeth',
 'Boulos, Mrs. Joseph (Sultana)',
 'Braund, Mr. Owen Harris',
 'Burke, Mr. Jeremiah',
 'Byles, Rev. Thomas Roussel Davids',
 'Caldwell, Master. Alden Gates',
 'Cann, Mr. Ernest Charles',
 'Carrau, Mr. Francisco M',
 'Celotti, Mr. Francesco',
 'Chaffee, Mr. Herbert Fuller',
 'Christmann, Mr. Emil',
 'Chronopoulos, Mr. Apostolos',
 'Coelho, Mr. 

In [10]:
sorted(titanic["Name"])[0:5:1]# Check the first 5 sorted names

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan']

In [11]:
titanic[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [12]:
## Adding a new column

titanic["new_column"]="New Column"
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  new_column  
0      0         A/5 21171   7.2500   NaN        S  New Column  
1      0          PC 17599  71.2833   C85        C  New Column  
2      0  STON/O2. 3101282   7.9250   NaN        S  New Column  
3      0            113803  53.1000  C123        S  New Column  
4      0            373450   8.0500   NaN        S  New Column

In [13]:
# NaN
titanic["Cabin"][0:15] 

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [14]:
# Name of the columns

titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'new_column'],
      dtype='object')

In [15]:
new_Pclass = pd.Categorical(titanic["Sex"])

new_Pclass

['male', 'female', 'female', 'female', 'male', ..., 'female', 'male', 'male', 'male', 'male']
Length: 156
Categories (2, object): ['female', 'male']

In [16]:
titanic["Cabin"].unique() 

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [18]:
titanic["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [19]:
missing = np.where(titanic["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [20]:
titanic[5:6]

PassengerId  Survived  Pclass              Name   Sex  Age  SibSp  Parch  \
5            6         0       3  Moran, Mr. James  male  NaN      0      0   

   Ticket    Fare Cabin Embarked  new_column  
5  330877  8.4583   NaN        Q  New Column

In [21]:
np.where(titanic["Fare"]==max(titanic["Fare"]))

(array([27, 88]),)

In [22]:
titanic.iloc[np.where(titanic["Fare"]==max(titanic["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare        Cabin Embarked  new_column  
27  19.0      3      2  19950  263.0  C23 C25 C27        S  New Column  
88  23.0      3      2  19950  263.0  C23 C25 C27        S  New Column

In [23]:
## Creating data frame from dict

mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]

df = pd.DataFrame(mydict)
df

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000


## loc vs iloc

### loc gets rows (or columns) with particular labels from the index.
### iloc gets rows (or columns) at particular positions in the index (so it only takes integers).

In [24]:
df = pd.DataFrame({'Age': [30, 20, 22, 40, 32, 28, 39],
                   'Color': ['Blue', 'Green', 'Red', 'White', 'Gray', 'Black',
                             'Red'],
                   'Food': ['Steak', 'Lamb', 'Mango', 'Apple', 'Cheese',
                            'Melon', 'Beans'],
                   'Height': [165, 70, 120, 80, 180, 172, 150],
                   'Score': [4.6, 8.3, 9.0, 3.3, 1.8, 9.5, 2.2],
                   'State': ['NY', 'TX', 'FL', 'AL', 'AK', 'TX', 'TX']
                   },
                  index=['Jane', 'Nick', 'Aaron', 'Penelope', 'Dean',
                         'Christina', 'Cornelia'])

df

Age  Color    Food  Height  Score State
Jane        30   Blue   Steak     165    4.6    NY
Nick        20  Green    Lamb      70    8.3    TX
Aaron       22    Red   Mango     120    9.0    FL
Penelope    40  White   Apple      80    3.3    AL
Dean        32   Gray  Cheese     180    1.8    AK
Christina   28  Black   Melon     172    9.5    TX
Cornelia    39    Red   Beans     150    2.2    TX

In [25]:
df.loc['Jane']

Age          30
Color      Blue
Food      Steak
Height      165
Score       4.6
State        NY
Name: Jane, dtype: object

In [26]:
df.iloc[0]

Age          30
Color      Blue
Food      Steak
Height      165
Score       4.6
State        NY
Name: Jane, dtype: object

In [27]:
df.loc[['Jane', 'Nick']]

Age  Color   Food  Height  Score State
Jane   30   Blue  Steak     165    4.6    NY
Nick   20  Green   Lamb      70    8.3    TX

In [28]:
df.iloc[0:2]

Age  Color   Food  Height  Score State
Jane   30   Blue  Steak     165    4.6    NY
Nick   20  Green   Lamb      70    8.3    TX

In [29]:
df.loc[['Jane', 'Nick'], ['Age', 'Color']]

Age  Color
Jane   30   Blue
Nick   20  Green

In [30]:
df.loc[df['Age'] < 30]

Age  Color   Food  Height  Score State
Nick        20  Green   Lamb      70    8.3    TX
Aaron       22    Red  Mango     120    9.0    FL
Christina   28  Black  Melon     172    9.5    TX

In [31]:
df.iloc[(df['Age'] < 30).values]

Age  Color   Food  Height  Score State
Nick        20  Green   Lamb      70    8.3    TX
Aaron       22    Red  Mango     120    9.0    FL
Christina   28  Black  Melon     172    9.5    TX

In [32]:
df['Age'] < 30

Jane         False
Nick          True
Aaron         True
Penelope     False
Dean         False
Christina     True
Cornelia     False
Name: Age, dtype: bool

In [33]:
(df['Age'] < 30).values

array([False,  True,  True, False, False,  True, False])